### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by 0xilly** [illyohs/CivilMagicks#2]
- [ ] ManaStar Generation based on biomes
- [ ] Mana transferring between different nodes
- [ ] Rendering for the mana stars
